import { createFileRoute } from "@tanstack/react-router";

// Public OG-image endpoint used in <meta og:image> for /jobs/$jobId.
// Job posters are generated by `generateJobOgImage` and stored in Firebase
// Storage with their public URL saved on the job document (`og_image_url`).
// This handler resolves the job and redirects crawlers to that public URL.
export const Route = createFileRoute("/api/public/og/jobs/$file")({
  server: {
    handlers: {
      GET: async ({ params }) => {
        const file = params.file as string;
        // Accept "<jobId>.<ext>"; jobId is a Firestore doc id (not necessarily a UUID).
        const m = file.match(/^([A-Za-z0-9_-]+)\.(png|jpg|jpeg|webp)$/);
        if (!m) return new Response("Not found", { status: 404 });
        const jobId = m[1];

        try {
          const { getAdminDb } = await import("@/integrations/firebase/admin");
          const db = await getAdminDb();
          const snap = await db.collection("jobs").doc(jobId).get();
          const url = snap.exists ? (snap.data() as { og_image_url?: string }).og_image_url : null;
          if (!url) return new Response("Not found", { status: 404 });
          return new Response(null, {
            status: 302,
            headers: {
              Location: url,
              "Cache-Control": "public, max-age=86400",
            },
          });
        } catch {
          return new Response("Not found", { status: 404 });
        }
      },
    },
  },
});
